### ISSUE TITLE
To-do App - React project

### ISSUE THREAD

**Issue by kashishahuja2002** [Himanshu-Verma-10/Basic_React_projects#6]
A simple react project for maintaining To-Dos.

**Comment by kashishahuja2002** [comment]
Please assign this issue to me.

**Comment by kashishahuja2002** [comment]
https://github.com/Himanshu-Verma-10/Basic_React_projects/pull/7

**Comment by pallavi2031** [comment]
It will be my pleasure if you will assign this issue.
